name: Tests CI
on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:
jobs:
  tests:
    strategy:
      matrix:
        version: ["macos-26", "macos-15"]
      fail-fast: false
    runs-on: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v7

      - name: Update Homebrew
        run: brew update
      - name: Install shellcheck
        run: brew install shellcheck
      - name: Run shellcheck
        run: shellcheck mac -e SC2039
      - name: Unlink preinstalled node
        run: brew unlink node
      - name: Run mac
        run: sh mac
